Add Endpoint /testing/history
marlon360/rki-covid-api pull request #178
Opened 2021-04-15 00:39 UTC by Rubber1Duck

add a ne endpoint /testing/history witch provides the  number of weekly done PCR-tests, the number of positive test in this week, the positiv tests quote and the number of transmitting laboratories.
Fix #176

2021-04-15 00:46 UTC, Rubber1Duck commented
so, nu aber :-)

2021-04-16 16:15 UTC, beyerleinf commented
Hey @Rubber1Duck, super Arbeit! Bei "PositivQuote" und "PositivTesting" fehlt nur ein "e" :) Ich glaube bei den properties sollte der erste Buchstabe auch klein sein :)

2021-04-16 16:34 UTC, Rubber1Duck commented
> 
> 
> Hey @Rubber1Duck, super Arbeit! Bei "PositivQuote" und "PositivTesting" fehlt nur ein "e" :) Ich glaube bei den properties sollte der erste Buchstabe auch klein sein :)

Danke für die Tipps! erledigt

2021-04-16 16:38 UTC, beyerleinf commented
Looks good!

2021-04-16 23:01 UTC, Rubber1Duck commented
@marlon360 merge please. i have ready another endpoint /maps/districts/history/:days witch gives the history districts map up to 30 days in the past! but first this PR must merged!

2021-04-18 18:39 UTC, marlon360 requested changes
Hi @Rubber1Duck!
Thank you for this PR.
I would like to change the naming of some attributes and some Englisch translations.

2021-04-18 18:39 UTC, marlon360 commented on src/data-requests/testing.ts
> +    countTesting: number,
Can we change this to `performedTests`?

2021-04-18 18:39 UTC, marlon360 commented on src/data-requests/testing.ts
> +    positiveTesting: number,
Can we change this to `positiveTests`?

2021-04-18 18:39 UTC, marlon360 commented on src/data-requests/testing.ts
> +    positiveQuote: number,
Can we change this to `positivityRate`?

2021-04-18 18:39 UTC, marlon360 commented on src/data-requests/testing.ts
> +    countLaboratories: number
Can we change this to `laboratoryCount`?

2021-04-18 18:39 UTC, marlon360 commented on docs/index.md
> +- Count of the weekly carried out PCR-Tests, Count of positiv tests and positiv quotes
Better "Number of performed PCR-test, number of positive tests and positivity rate"

2021-04-18 18:39 UTC, marlon360 commented on docs/endpoints/testing.md
> +`countTesting` Number PCR-tests executed.
"Number of performed PCR-tests"

2021-04-18 18:39 UTC, marlon360 commented on docs/endpoints/testing.md
> +`positiveTesting` Number PCR-tests witch are COVID-19 positiv
"Number of positive PCR-tests"

2021-04-18 18:39 UTC, marlon360 commented on docs/endpoints/testing.md
> +`positiveQuote` Ouote of COVID-19 positive tests
"The rate of positive PCR-tests"

2021-04-18 18:39 UTC, marlon360 commented on docs/endpoints/testing.md
> +`countLaboratories` Number Laboratories witch transmitted Data to RKI
"Number of laboratories which transmitted data to the RKI"

2021-04-18 18:39 UTC, marlon360 commented on src/data-requests/testing.ts
> +            countLaboratories: entry['Anzahl übermittelnder Labore']
Please add a "tab" to each line for better formatting.

2021-04-18 18:39 UTC, marlon360 commented on README.md
> +- Count of the weekly carried out PCR-Tests, Count of positiv tests and positiv quotes
Better "Number of performed PCR-test, number of positive tests and positivity rate"

2021-04-18 18:42 UTC, marlon360 commented
> @marlon360 merge please. i have ready another endpoint /maps/districts/history/:days witch gives the history districts map up to 30 days in the past! but first this PR must merged!
> and also merge PR #174 because of the documentation.
> thanks

Nice @Rubber1Duck!
Maybe consider using different branches for different PRs, so you can work on them simultaneously.

2021-04-18 19:42 UTC, Rubber1Duck commented
> 
> 
> > @marlon360 merge please. i have ready another endpoint /maps/districts/history/:days witch gives the history districts map up to 30 days in the past! but first this PR must merged!
> > and also merge PR #174 because of the documentation.
> > thanks
> 
> Nice @Rubber1Duck!
> Maybe consider using different branches for different PRs, so you can work on them simultaneously.

Hi Marlon, of course i will do the changes!
I'm fighting with github ......... :-) i hope we will get good friends soon, but at the moment i despair sometimes

2021-04-18 20:09 UTC, Rubber1Duck commented
changes done

2021-04-18 20:37 UTC, marlon360 commented
Thanks!
But I think in this PR are now changes that don’t belong here. Could you clean that up?

2021-04-18 21:56 UTC, Rubber1Duck commented
New PR #180 !

2021-04-18 21:56 UTC, closed without merging