new endpoint for frozen-incidence
marlon360/rki-covid-api pull request #207
Opened 2021-05-03 07:53 UTC by PatrickHaussmann

the discussion for this pull request is in #204. also, it would fix problems like in #148 

rki publishes the frozen incidence values in an excel file. This file is also used for the "emergency brake" (Notbremse). 
Please look here [rki.de/inzidenzen](https://rki.de/inzidenzen).

Todos before it can be merged
- [x] write functions for `data-requests`
- [x] write functions for `responses`
- [ ] document the difference to e.g. `/districts/history/incidence`
- [ ] direct users to use this endpoint if they want data used for political decisions or TV/newspapers
- [ ] implement `/districts/history/:days/incidence`

fix #148 
fix #204

2021-05-03 07:58 UTC, PatrickHaussmann commented
after looking over it again, i thought that "src/responses/frozen-incidence.ts" should probably not be an extra file, rather it should be added to "src/responses/districts.ts

2021-05-03 11:35 UTC, Rubber1Duck commented
> after looking over it again, i thought that `src/responses/frozen-incidence.ts` should probably not be an extra file, rather it should be added to `src/responses/districts.ts`

good point, make sense

>     * [ ]  implement `/districts/history/:days/incidence`

do you meen `/districts/history/frozen-incidence/:days` (argument :days is after incidence!)
`/districts/history/incidence/:days` already exists!

then maybe `/districts/:district/history/frozen-incidence` and `/districts/:district/history/frozen-incidence/:days` are missing, too

you have to edit `/docs/.vuepress/config.js` and README.md, too.

2021-05-03 12:42 UTC, Rubber1Duck commented
> you have to edit `/docs/.vuepress/config.js` and README.md, too.

sorry, if you move the functions to district.ts edit of `/docs/.vuepress/config.js` is not nessesary! because the new  links are part of /districts

2021-05-03 14:23 UTC, Rubber1Duck commented
> sorry, if you move the functions to district.ts edit of `/docs/.vuepress/config.js` is not nessesary! because the new links are part of /districts

For README.md also

2021-05-03 14:26 UTC, Rubber1Duck approved these changes
so far, looks fine

2021-05-03 15:07 UTC, PatrickHaussmann commented
The code changes are done so far (except for appreciated suggested changes).
What are your comments?

I think i need help documenting and explaining what the difference is to incidence. 
I'm also not sure in which places this should best be done

2021-05-03 15:23 UTC, Rubber1Duck requested changes

2021-05-03 15:23 UTC, Rubber1Duck commented on README.md
> +**Incidence data**
That should be `**Frozen-Incidence data**`
the other updating incidences are calculated from weekly new cases

2021-05-03 15:33 UTC, Rubber1Duck commented
> I think i need help documenting and explaining what the difference is to `incidence`.
> I'm also not sure in which places this should best be done

here is the german text witch described the difference very well, "just" translate it :-)
Gemäß § 28b IfSG veröffentlicht das RKI für alle Landkreise und kreisfreien Städte fortlaufend die 7-Tage-Inzidenz.
Bei den 7-Tage-Inzidenzen für frühere Tage muss berücksichtigt werden, dass es sich um die jeweils an dem angegebenen Tag berichteten Werte handelt, die nicht durch an Folgetagen nachübermittelte Fälle aktualisiert werden (für den Berichtstag "eingefrorene" Werte).
Diese Werte sind für das In- und Außerkrafttreten der bundeseinheitlichen Maßnahmen nach § 28b des Infektionsschutzgesetzes („Bundesnotbremse“) maßgeblich. Die Zugrundelegung der „eingefrorenen“ Werte stellt sicher, dass die Werte keinen Schwankungen unterliegen und sich die von den Maßnahmen Betroffenen auf das In- bzw. Außerkrafttreten dieser mit einem zeitlichen Vorlauf einstellen können.
Da in der Regel an den Folgetagen noch Fälle mit einem Meldedatum an einem der Vortage nachübermittelt werden, erhöht sich die 7-Tage-Inzidenz bei rückwirkender Betrachtung. Diese Inzidenzwerte entsprechen den "alten" Inzidenzwerten! welche unter den Teillinks xxxxxxxxx/incidence/xxxxxxxx verfügbar sind.

this should be part of frozen-incidence.md i think !?

2021-05-03 18:02 UTC, marlon360 requested changes
I would like to change the way we parse the file a bit. I am going to prepare something.

2021-05-03 18:02 UTC, marlon360 commented on src/data-requests/frozen-incidence.ts
> +  }
We don't need to limit the days (this is only needed for the arcgis endpoints)

2021-05-03 18:02 UTC, marlon360 commented on src/data-requests/frozen-incidence.ts
> +  const json = XLSX.utils.sheet_to_json(sheet);
We should parse the sheet in a better way. The keys of the object should be the headers.

2021-05-03 18:02 UTC, marlon360 commented on src/data-requests/frozen-incidence.ts
> +    const ags = element[keys.shift()].toString().padStart(5, "0");
Working with shift unpredictable, we should access the row by name.

2021-05-03 18:06 UTC, marlon360 commented
```TS
import axios from "axios";
import XLSX from "xlsx";
import { getDateBefore, RKIError } from "../utils";
import { ResponseData } from "./response-data";

export interface FrozenIncidenceData {
  ags: string;
  name: string;
  history: {
    date: string;
    value: number;
  }[];
}

export async function getFrozenIncidenceHistory(
  days?: number,
  ags?: string
): Promise<ResponseData<FrozenIncidenceData[]>> {
  const response = await axios.get(
    "https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab.xlsx?__blob=publicationFile",
    {
      responseType: "arraybuffer",
    }
  );
  const data = response.data;
  if (data.error) {
    throw new RKIError(data.error, response.config.url);
  }

  var workbook = XLSX.read(data, { type: "buffer", cellDates: true });
  const sheet = workbook.Sheets["LK_7-Tage-Inzidenz"];
  // table starts in row 5 (parameter is zero indexed)
  const json = XLSX.utils.sheet_to_json(sheet, { range: 4 });

  // date is in cell A2
  const dateString = sheet["A2"].v.replace("Stand: ", "");
  const lastUpdate = new Date(dateString);

  const districts = json.map((district) => {
    const name = district["LK"];
    const ags = district["LKNR"].toString().padStart(5, "0");

    let history = [];

    // get all date keys
    const dateKeys = Object.keys(district);
    // ignore the first three elements (rowNumber, LK, LKNR)
    dateKeys.splice(0, 3);
    dateKeys.forEach((dateKey) => {
      const date_pattern = /(\d{2})\.(\d{2})\.(\d{4})/;
      const date = new Date(
        dateKey.toString().replace(date_pattern, "$3-$2-$1")
      );
      history.push({ weekIncidence: district[dateKey], date });
    });

    if (days != null) {
      const reference_date = new Date(getDateBefore(days));
      history = history.filter((element) => element.date > reference_date);
    }

    return { ags, name, history };
  });

  return {
    data: districts,
    lastUpdate: lastUpdate,
  };
}

```

2021-05-03 18:22 UTC, PatrickHaussmann commented
> I would like to change the way we parse the file a bit. I am going to prepare something.

thank you for these very good improvement suggestions

2021-05-03 19:47 UTC, marlon360 requested changes
I'd like to move the `ags` filtering to `getFrozenIncidenceHistory`.

2021-05-03 19:47 UTC, marlon360 commented on src/responses/districts.ts
> +  }
Let's move the `ags` filtering to the data-request and use `filter` of `Array`.

2021-05-03 19:47 UTC, marlon360 commented on src/data-requests/frozen-incidence.ts
> +
Let's add the `ags` filtering here.

2021-05-03 19:49 UTC, marlon360 commented
districts.ts:
```TS
interface FrozenIncidenceHistoryData extends IResponseMeta {
  data: {
    [key: string]: FrozenIncidenceData
  }
}

export async function FrozenIncidenceHistoryResponse(
  days?: number,
  ags?: string
): Promise<FrozenIncidenceHistoryData> {
  const frozenIncidenceHistoryData = await getFrozenIncidenceHistory(days, ags);

  let data = {};
  frozenIncidenceHistoryData.data.forEach(historyData => {
    data[historyData.ags] = historyData
  });

  return {
    data: data,
    meta: new ResponseMeta(frozenIncidenceHistoryData.lastUpdate),
  };
}

```

frozen-incidence.ts:

```TS
  let districts = json.map((district) => {
    const name = district["LK"];
    const ags = district["LKNR"].toString().padStart(5, "0");

    let history = [];

    // get all date keys
    const dateKeys = Object.keys(district);
    // ignore the first three elements (rowNumber, LK, LKNR)
    dateKeys.splice(0, 3);
    dateKeys.forEach((dateKey) => {
      const date_pattern = /(\d{2})\.(\d{2})\.(\d{4})/;
      const date = new Date(
        dateKey.toString().replace(date_pattern, "$3-$2-$1")
      );
      history.push({ weekIncidence: district[dateKey], date });
    });

    if (days != null) {
      const reference_date = new Date(getDateBefore(days));
      history = history.filter((element) => element.date > reference_date);
    }

    return { ags, name, history };
  });


  if (ags != null) {
    districts = districts.filter((district) => district.ags === ags);
  }
```

2021-05-03 20:17 UTC, marlon360 approved these changes

2021-05-03 20:18 UTC, marlon360 commented
Great job @PatrickHaussmann!
We can add the descriptions in the docs later.

2021-05-03 20:18 UTC, merged

2021-05-03 20:42 UTC, Rubber1Duck commented
unfortnatly the list is unsorted!
![frozen](https://user-images.githubusercontent.com/6493772/116931035-ccef3a00-ac60-11eb-89d0-6e3cd2486c77.png)

2021-05-03 20:44 UTC, marlon360 commented
The list is sorted alphabetically by name.

2021-05-03 20:51 UTC, Rubber1Duck commented
sure?
![frozen2](https://user-images.githubusercontent.com/6493772/116931981-04121b00-ac62-11eb-8be0-674bedeedd9b.png)
but if so thats not in line with all the other lists!

2021-05-04 08:48 UTC, Rubber1Duck commented
is it a big problem to resort this by the key?

2021-05-04 09:34 UTC, PatrickHaussmann commented
I believe that this is not possible. 
the order of an object "does not depend on how an object is defined" [source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries).
[or here is another good discussion about this](https://stackoverflow.com/questions/30076219/does-es6-introduce-a-well-defined-order-of-enumeration-for-object-properties)

another possibility I could imagine is write a custom `toJSON` function to be used by `res.json` in `server.ts` in which we could sort the entries by ags


it may well be that I am overlooking something

2021-05-04 10:36 UTC, marlon360 commented
I think it does not make sense to order keys. Only arrays should have a defined order (e.g. the history array).
We use keys to access certain districts directly, without having to loop through them.

If you want to order the keys, you can do it inside your application.
- get key array
- order keys the way you want
- loop through ordered keys and access associated value

2021-05-04 10:59 UTC, Rubber1Duck commented
Okay