rValue history of germany
marlon360/rki-covid-api pull request #208
Opened 2021-05-03 09:18 UTC by PatrickHaussmann

this would fix #95

There are a few things i am not sure about:

1. is the name `/germany/history/rValue` ok?
2. the first 4 days have a r-value of `null`. Should we remove them?

2021-05-03 11:44 UTC, Rubber1Duck commented
>     1. is the name `/germany/history/rValue` ok?
> 
>     2. the first 4 days have a `r-value` of `null`. Should we remove them?
> 
>     3. `lastUpdate` is set to `now`. Is there a better way get the `lastUpdate` value
1. think thats okay
2. yes, that makes sense.
3. maybe as in vaccination.ts `const response = await axios.get(
    `https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquotenmonitoring.xlsx?__blob=publicationFile`,
    {
      responseType: "arraybuffer",
    }
  );
  const data = response.data;
  const lastModified = response.headers["last-modified"];
  const lastUpdate = lastModified != null ? new Date(lastModified) : new Date();`

2021-05-03 12:05 UTC, Rubber1Duck commented on src/data-requests/r-value.ts
> +  if (data.error) {
const lastModified = response.headers["last-modified"];
  const lastUpdate = lastModified != null ? new Date(lastModified) : new Date();

2021-05-03 12:05 UTC, Rubber1Duck commented on src/data-requests/r-value.ts
>      lastUpdate: rData.date,
lastUpdate: lastUpdate,

2021-05-03 12:55 UTC, PatrickHaussmann commented
if we would have:
`const lastUpdate = history[history.length - 1].date;`

then it would be in line with what we return in the function `getRValue`.
Alternatively, we could also get it from the headers in `getRValue`.
what is your take on this?

2021-05-03 13:05 UTC, Rubber1Duck commented
both should be the same and it is a good idea to take it from the header! My mind ....

2021-05-03 13:11 UTC, Rubber1Duck commented
`/germany/history/rValue/:days` would be very nice!

2021-05-03 13:12 UTC, PatrickHaussmann commented
> `/germany/history/rValue/:days` would be very nice!

I am already in the process :)

2021-05-03 14:10 UTC, Rubber1Duck requested changes
Dont forget README.md!

2021-05-03 14:13 UTC, PatrickHaussmann commented
i am very sorry that it is not clear to me. but what should i change/add in `README.md`?

2021-05-03 14:18 UTC, Rubber1Duck approved these changes
Sorry, there is no changes needed in README.md!
My fault

2021-05-03 14:19 UTC, Rubber1Duck commented
God job!
for me that looks all fine!

2022-12-16 22:59 UTC, Rubber1Duck commented
is replaced by new PR

2022-12-16 22:59 UTC, closed without merging