Add featured project
marlon360/rki-covid-api pull request #226
Opened 2021-05-19 10:49 UTC by laurenzfg

Include Vacstats in featured projects

2021-05-26 07:45 UTC, Rubber1Duck requested changes
You have to add your project to /docs/index.md, too!

2021-05-27 17:43 UTC, Rubber1Duck requested changes

2021-05-27 17:43 UTC, Rubber1Duck commented on docs/index.md
> +- Web App for vaccination numbers which issues a Push Notification whenever the new vaccination numbers are available (https://vacstats.laurenzfg.com)
please add "[https://vacstats.laurenzfg.com]" bevor "(https://vacstats.laurenzfg.com)"

2021-05-28 19:03 UTC, laurenzfg commented on docs/index.md
> +- Web App for vaccination numbers which issues a Push Notification whenever the new vaccination numbers are available (https://vacstats.laurenzfg.com)
sure! sorry for not complying to markdown in my PR.

2021-05-28 19:26 UTC, Rubber1Duck approved these changes

2021-05-28 19:28 UTC, Rubber1Duck commented
No that looks fine to me! @marlon360 has to merge this!

2021-10-12 15:44 UTC, laurenzfg commented
hey @marlon360
I am currently reviewing my open PRs and I would love to either close or have this PR merged. Do you have capacity to merge this?

On an unrelated side note: I will change the API host of my project to your public node, since I don't wamt to keep my fork up forever.

2021-12-13 18:52 UTC, merged