Added my Project (cct.greeninc.ga)
marlon360/rki-covid-api pull request #360
Opened 2021-12-07 15:26 UTC by nilsbentlage

I built my own svelte pwa to display some often used metrics, depending on the "Landkreise" you can choose. Pre-Configured are the ones around my hometown.

2021-12-07 19:13 UTC, marlon360 requested changes
@nilsbentlage Thanks for the PR.

Could you also add your changes to /docs/index.md
(https://github.com/marlon360/rki-covid-api/blob/v2/docs/index.md)

2021-12-13 19:00 UTC, Rubber1Duck requested changes

2021-12-13 19:00 UTC, Rubber1Duck commented on docs/index.md
> +- Casumer Corona Tracker - Eine Svelte PWA zur Überwachung frei konfigurierbarer Landkreise (https://cct.greeninc.ga)
Please add `[https://https://cct.greeninc.ga]` befor `(https://cct.greeninc.ga)`
resulting in `- Casumer Corona Tracker - Eine Svelte PWA zur Überwachung frei konfigurierbarer Landkreise [https://https://cct.greeninc.ga](https://cct.greeninc.ga)`

2021-12-13 22:43 UTC, Rubber1Duck approved these changes

2021-12-13 22:55 UTC, Rubber1Duck commented on docs/index.md
> +- Casumer Corona Tracker - Eine Svelte PWA zur Überwachung frei konfigurierbarer Landkreise (https://cct.greeninc.ga)
already done by me

2021-12-17 11:47 UTC, marlon360 approved these changes

2021-12-17 11:47 UTC, merged