Change Dockerfile to make it compatible to arm64, arm32v7 Architectures
marlon360/rki-covid-api pull request #75
Opened 2021-01-22 20:29 UTC by Rubber1Duck

Signed-off-by: Peter Markewitz <peter@markewitz.org>
This change make it possible to build the Docker Image on Linux/AMD64, Linux/ARM64 and Linux/ARM32V7 Architectures.
Maybe also Linux/ARM32V6 is possible (not tested yet)
by the Way the resulting image for AMD64 ist smaler than bevor!

2021-01-23 19:49 UTC, marlon360 commented
Hey @Rubber1Duck 

This looks pretty good, thank you very much!
But let's try lowering the image size even more by using `node:12-alpine`

Unfortunately `alpine` does not have `apt-get`.

I have found a different solution, but I cannot test it on the Raspberry PI.
Could you do me a favor and test this Dockerfile on your Raspberry PI:

```dockerfile
FROM node:12-alpine

# Add libvips
RUN apk add --upgrade --no-cache vips-dev build-base --repository http://dl-3.alpinelinux.org/alpine/edge/testing

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

RUN npm install pm2 -g

# Bundle app source
COPY . .

RUN npm run build

EXPOSE 8080
CMD ["pm2-runtime", "dist/server.js", "-i", "-1"]
```

2021-01-23 23:12 UTC, Rubber1Duck commented
Hi Marlon,

do you know this site [https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/](url)

unfortnetly this Dockerfile is not running for ARM64 and ARM32V7!

There is a similar Error at Step RUN npm install as bevor:

#10 234.7 > sharp@0.27.0 install /usr/src/app/node_modules/sharp
#10 234.7 > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
#10 234.7
#10 238.0 info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-linuxmusl-arm64v8.tar.br
#10 238.9 ERR! sharp Prebuilt libvips 8.10.5 binaries are not yet available for linuxmusl-arm64v8
#10 238.9 info sharp Attempting to build from source via node-gyp but this may fail due to the above error

sharp 0.27.0 needs libvips 8.10.5 an Alpine Linux has only 8.5.8 or so.

What i not understand is:  the file under [https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-linuxmusl-arm64v8.tar.br](url) exists and nevertheless that end in an Error ..............

but for ARM32V7 the file do not exists!

I dont know ALPINE Linux aund i have no idea how to fix this.

2021-01-23 23:30 UTC, marlon360 commented
Alright, thank you for trying this!

I would like to use the smaller `alpine` image as default, but keep your `Dockerfile` as an arm version and tag it with `v2-arm`.

Could you rename your docker file to `arm.Dockerfile`?

Thanks again for this great enhancement!

2021-01-23 23:31 UTC, marlon360 requested changes
Keep original `Dockerfile` and rename the new one to `arm.Dockerfile`

2021-01-24 23:29 UTC, Rubber1Duck commented
Hi Marlon,
last night i decided to study Alpine Linux to bring the architectures AMD64, ARM64 and ARM32V7 on one Dockerfile.
In the following picture you can see what Imagesizes i'm able to reach ............
![node_12-Alpine](https://user-images.githubusercontent.com/6493772/105646942-1b8f7a00-5ea3-11eb-90c5-f001f5f6aadd.png)
Okay what do you want? one Dockerfile for AMD64 and another for ARM64/ARM32V7, or only one Dockerfile for all 3 architektures. This looks like this:

```
FROM node:12-alpine

# common build flags
ENV CFLAGS=-O3
ENV CXXFLAGS=-O3

WORKDIR /tmp

# build dependencies, compile vips-8.10.5  and cleanup
RUN apk add --no-cache --virtual .build-stuff \
        gcc \
        g++ \
        make \
        wget \
        gtk-doc \
        pkgconfig \
        binutils \
        libc6-compat && \
        apk add --no-cache \
        glib-dev \
        expat-dev \
        tiff-dev \
        libpng \
        fftw-dev && \
        wget https://github.com/libvips/libvips/releases/download/v8.10.5/vips-8.10.5.tar.gz && \
        tar xzf vips-8.10.5.tar.gz && \
        rm -rf vips-8.10.5.tar.gz && \
        cd vips-8.10.5 && \
        ./configure && \
        make && \
        make install && \
        cd .. && \
        rm -rf vips-8.10.5 && \
        apk del .build-stuff

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# until npm Install Sharp is compiled so we need some compiling tools
# so first install the tools, prozess npm install and then deinstall the tools right now
RUN apk add --no-cache --virtual .build-stuff2 \
        gcc \
        g++ \
        make \
        binutils \
        libc6-compat && \
        npm install && \
        apk del .build-stuff2
# If you are building your code for production
# RUN npm ci --only=production

RUN npm install pm2 -g

# Bundle app source
COPY . .

RUN npm run build

EXPOSE 8080
CMD ["pm2-runtime", "dist/server.js", "-i", "-1"]
```

Your dessission?

2021-01-25 00:11 UTC, marlon360 commented
@Rubber1Duck Thanks for looking closer into the `alpine` image.

Unfortunately when I use this Dockerfile on my machine, the map images don't work.

2021-01-25 07:35 UTC, Rubber1Duck commented
> 
> 
> @Rubber1Duck Thanks for looking closer into the `alpine` image.
> 
> Unfortunately when I use this Dockerfile on my machine, the map images don't work.

i will have a look on it today

2021-01-25 13:24 UTC, Rubber1Duck commented
found the mistake, libvips need gif support, i thought png is enough, will fix this later, have to do other things now

2021-01-26 18:27 UTC, Rubber1Duck commented
close This PR, done a new one!

2021-01-26 18:27 UTC, closed without merging